### ISSUE TITLE
Validate Issuer of SAML response

### ISSUE THREAD

**Issue by takehikokodama** [HENNGE/minisaml#11]
Issuer of SAML response should be validated.

---

https://github.com/HENNGE/minisaml/blob/5bdf2fc7b2c668571e1c35858559914919cc1b7a/src/minisaml/response.py#L90

Audience of SAML response = SP's entity ID -> validated here
Issuer of SAML response = IdP's entity ID -> not validated

**Comment by ojii** [comment]
> Issuer of SAML response = IdP's entity ID -> not validated

It is not validated by default, though you could validate `response.issuer` yourself. The logic behind not requiring to validate it is that the certificate of the issuer is already validated, so I did not see the value in requiring it to be validated. 

Maybe this should be changed though. Could you explain why you think this is necessary?

**Comment by takehikokodama** [comment]
Some multi tenant IdP services have issuer for each tenant with same certificate like:
Issuer for tenant1:`https://idp.example.com/tenant1.com`
Issuer for tenant2: `https://idp.example.com/tenant2.com`

In this case, if issuer is not validated in a SP, tenant1 users can be spoofing tenant2 users in the SP services, and vice versa.

**Comment by dimaqq** [comment]
> Some multi tenant IdP services have issuer for each tenant with same certificate like:
> Issuer for tenant1:`https://idp.example.com/tenant1.com`
> Issuer for tenant2: `https://idp.example.com/tenant2.com`
> 
> In this case, if issuer is not validated in a SP, tenant1 users can be spoofing tenant2 users in the SP services, and vice versa.

And you are saying that both issuers use same certificate?

**Comment by ojii** [comment]
> In this case, if issuer is not validated in a SP, tenant1 users can be spoofing tenant2 users in the SP services, and vice versa.

Is this something minisaml can solve though? The ACS might not know which tenant is expected and instead use the `response.issuer` field to select the tenant. 

If `validate_response` were to check the IdP issuer it would force the users of this library to use per-tenant ACS endpoints, and I'm not sure this is something that this library should decide.

**Comment by takehikokodama** [comment]
> Is this something minisaml can solve though? The ACS might not know which tenant is expected and instead use the `response.issuer` field to select the tenant.

SP has to identify uses by combination of **issuer** and **user** (NameID or other unique attribute)
Means, following 2 users must be treated as different users in SP, of course.
- **user** `tanaka` ,  **issuer** `https://idp.example.com/tenant1.com`
- **user** `tanaka` ,  **issuer** `https://idp.example.com/tenant2.com`

As long as SP validate both **user** and **issuer** correctly, ACS endpoints can be single even for multi tenant.

**Comment by ojii** [comment]
This has been implemented in 22.7.
