### ISSUE TITLE
validate StatusCode

### ISSUE THREAD

**Issue by ojii** [HENNGE/minisaml#16]
`minisaml.response.validate_response` should probably validate `{urn:oasis:names:tc:SAML:2.0:protocol}StatusCode` ([SAML Core 2.0, 3.2.2.2](https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf)). However, this is on the `{urn:oasis:names:tc:SAML:2.0:protocol}Response` and `minisaml` supports either the `{urn:oasis:names:tc:SAML:2.0:protocol}Response` or the `{urn:oasis:names:tc:SAML:2.0:assertion}Assertion` to be signed, so the question is, how should the validation behave if only the `{urn:oasis:names:tc:SAML:2.0:assertion}Assertion` is signed (and thus the value of `{urn:oasis:names:tc:SAML:2.0:protocol}StatusCode` could have been tampered with)?

**Comment by dimaqq** [comment]
my 2c: unsigned bits should be erased

**Comment by ojii** [comment]
> my 2c: unsigned bits should be erased

that is the case currently. the first thing `validate_response` does it get the signature, get the signed element, check signature. After that, everything but the signed element is discarded.

So should the value of `StatusCode` be checked if it's in the signed element (aka if the Response was signed as opposed to the Assertion) and just ignored otherwise?

**Comment by takehikokodama** [comment]
I think the value of `StatusCode` is not important especially when it's succeeded. So, I think you don't need to validate it.

**Comment by ojii** [comment]
> I think the value of `StatusCode` is not important especially when it's succeeded. So, I think you don't need to validate it.

agreed.
