### ISSUE TITLE
README example does not match API

### ISSUE THREAD

**Issue by Glocktober** [HENNGE/minisaml#25]
The example in the README.md in the section for `validate_response()`  does not include the idp_issuer parameter.

Have to say adding this parameter within the same API broke code; it would have been better if it had been an optional parameter or a different call name.

**Comment by ojii** [comment]
> Have to say adding this parameter within the same API broke code 

the changelog clearly indicates that this version includes a breaking change

> it would have been better if it had been an optional parameter or a different call name.

validating the idp issuer is crucial if the idp serves multiple tenants with the same certificate, that's why it's a required argument.

**Comment by ojii** [comment]
fixed the readme in 24ee69a, thank you for reporting this.
