### ISSUE TITLE
Response with multple AttributeValue in Attribute element fails

### ISSUE THREAD

**Issue by Glocktober** [HENNGE/minisaml#7]
multiple AttributeValue Attributes in IDP response cause failure - the code seems to insist on single value attributes.

IDP response include attribute format such as:

```
 ...
<AttributeStatement>
 ...
      <Attribute Name="groups">
        <AttributeValue>RemoteAccessExternal</AttributeValue>
        <AttributeValue>occdev</AttributeValue>
        <AttributeValue>sysadmin</AttributeValue>
      </Attribute>
 ...
</AttributeStatement>
 ...
```
Causes MultipleElementsFound exception:

```
(venv) rkras-mbp17:azsel rkras$ python bug.py 
Traceback (most recent call last):
  File "bug.py", line 14, in <module>
    resp = validate_response(
  File "/Library/WebServer/Documents/azsel/minisaml/response.py", line 103, in validate_response
    value = find_or_raise(attribute, "./saml:AttributeValue").text
  File "/Library/WebServer/Documents/azsel/minisaml/internal/utils.py", line 8, in find_or_raise
    return utils.find_or_raise(element, path, NAMESPACE_MAP)
  File "/Library/WebServer/Documents/v/venv/lib/python3.8/site-packages/minisignxml/internal/utils.py", line 82, in find_or_raise
    return exactly_one(element.findall(path, ns_map), path, element)
  File "/Library/WebServer/Documents/v/venv/lib/python3.8/site-packages/minisignxml/internal/utils.py", line 90, in exactly_one
    raise MultipleElementsFound(path, parent)
minisignxml.errors.MultipleElementsFound: ('./saml:AttributeValue', <Element {urn:oasis:names:tc:SAML:2.0:assertion}Attribute at 0x10f04ca40>)

```

Any number of AttributeValue statements > 1 cause this exception. 
Patching around this in minisignxml.internals.util:exactly_one to skip the num_results > 1 test skips the exception, but even so the multiple values are not returned in the response.attributes list. i.e. parsing code does not iterate over 'AttributeValue' tags as it does over 'Attribute' tags.

**Comment by Glocktober** [comment]
Here is something for consideration that fixes this issue.  Tested this against Azure AD.

minisaml.response.py in validate_response - replacing the 'find_or_raise' on 'AttributeValue' with a 'findall' and iterate over what is returned adding Attribute() entries.

```
103,114c103,112
<             for value_tag in attribute.findall("./saml:AttributeValue", NAMESPACE_MAP):
<                 value = value_tag.text
<                 extra_attributes = {k: v for k, v in attribute.attrib.items()}
<                 name = extra_attributes.pop("Name")
<                 format = extra_attributes.pop("NameFormat", None)
<                 attributes.append(
<                     Attribute(
<                         name=name,
<                         value=value,
<                         format=format,
<                         extra_attributes=extra_attributes,
<                     )
---
>             value = find_or_raise(attribute, "./saml:AttributeValue").text
>             extra_attributes = {k: v for k, v in attribute.attrib.items()}
>             name = extra_attributes.pop("Name")
>             format = extra_attributes.pop("NameFormat", None)
>             attributes.append(
>                 Attribute(
>                     name=name,
>                     value=value,
>                     format=format,
>                     extra_attributes=extra_attributes,
115a114
> 
```

**Comment by ojii** [comment]
Thank you for reporting this issue.

I think I'd rather have all the values of a single Attribute tag in a single Attribute instance, so this will need a slightly more involved fix.

**Comment by Glocktober** [comment]
The original code seems to permit multiple attribute tags with the same name but different values (indicated in the API docs as well.)
e.g.
```
Attribute Name="groups">
        <AttributeValue>RemoteAccessExternal</AttributeValue>
</Attribute>
 Attribute Name="groups">
        <AttributeValue>occdev</AttributeValue>
</Attribute>
 Attribute Name="groups">
        <AttributeValue>sysadmin</AttributeValue>
 </Attribute>
```
 I had thought that was from another idP I'm not familiar with and figured this change would coexist with that.

What I've done is to go through the response.attributes list to form a list for specific attributes e.g. groups=['sysadmin', 'occdev',] which is what I gathered from the docs was the recommendation.

**Comment by ojii** [comment]
@Glocktober could you provide me a full SAML Response you use so I can add a test for it to ensure my solution will work? Feel free to anonymize any of the personal information that may possibly be in it of course

**Comment by Glocktober** [comment]
I generated these using a throw-away test account.

Attached sample.txt an XML response that include 2 example - one for 'authmethodsreferences' and the other for 'groups'.  This was generated by Azure AD.

Attached sample2.txt an XML response with 'memberOf' with two entries. This one was generated by simpleSaml.

[sample2.txt](https://github.com/HENNGE/minisaml/files/5214463/sample2.txt)

[sample.txt](https://github.com/HENNGE/minisaml/files/5214430/sample.txt)
