### ISSUE TITLE
simplesaml and azure can not decode minisaml request

### ISSUE THREAD

**Issue by Glocktober** [HENNGE/minisaml#9]
Both Azure AD and simplesaml idp's give errors 

Azure reports: **"AADSTS750056: SAML message was not properly base64-encoded."**
SimpleSaml report: **"Exception: Error while inflating SAML message."**
Also with the url generated by get_request_redirect_url() - I can not decode the request using on line tools such as https://developer.pingidentity.com/en/tools-for-devs/saml-decoder.html

The problem appears to be the minisaml/request.py routine using _bin64.urlsafe_b64encode()_

Changing this to _bin64.b64encode()_ resolves the issue with simplesaml and azureAD, and decodes correctly in the ping tool.

If there is another idp requiring the urlsafe_b64encode, can a configuration option be provided to switch to the b64encode to allow this to be used with these other idps?

thanks

Here is test change that worked:
```
--- a/request.py
+++ b/request.py
@@ -25,7 +25,7 @@ def get_request_redirect_url(
     )
 
     query = {
-        "SAMLRequest": base64.urlsafe_b64encode(
+        "SAMLRequest": base64.b64encode(
             zlib.compress(request_xml)[2:-4]
         ).decode("utf-8")
     }
```

**Comment by dimaqq** [comment]
🤔 is it because of newlines in the base-64 output?

**Comment by ojii** [comment]
According to [SAML Bindings Errata 2.0  WD 5](https://www.oasis-open.org/committees/download.php/35387/sstc-saml-bindings-errata-2.0-wd-05-diff.pdf) Section 3.4.4.1 you are correct that the request encoding should use deflate, then base64 encode, then URL escaping (as part of the encoding of the URL later).
